[build-system]
requires = [
  "setuptools>=61.0"
  ]
build-backend = "setuptools.build_meta"

[project]
name = "airflow-unicore-integration"
version = "0.0.1-dev"
authors = [
  { name="Christian Böttcher", email="c.boettcher@fz-juelich.de" },
]
description = "Running Unicore Jobs from airflow DAGs."
readme = {file = "README.txt", content-type = "text/markdown"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 1 - Pre-Alpha",
    "Framework :: Apache Airflow :: Provider",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]



dependencies = [
    "pyunicore>=1.0.0",
    "apache-airflow==2.8.4"
]

[project.urls]
Homepage = "https://gitlab.jsc.fz-juelich.de/boettcher1/airflow_unicore_integration"
Issues = "https://gitlab.jsc.fz-juelich.de/boettcher1/airflow_unicore_integration/-/issues"

[project.entry-points."apache_airflow_provider"]
provider_info = "airflow_unicore_integration:get_provider_info"